### ISSUE TITLE
How to resend request for Camera Share

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-api#496]
We could use this endpoint:

/cameras/{id}/shares/requests

or a new one:

/cameras/{id}/shares/requests/resend

@liutingdu asks about this for iOS app.

**Comment by liutingdu** [comment]
The word 'iOS' was mentioned in this issue by mistake. I brought up that issue when I implement Sharing on Android, everything was done except there was no endpoint for resending share request, so I didn't do it in Android.

We haven't done anything related to Sharing on iOS.

The reason I don't want to use WebView is the user experience is much better by building Sharing natively. Now I still believe it's the right decision. ReactiveNative is worth to try for sharing code between Android & iOS but it still requires the resend endpoint.

I don't want to use SendGrid because if resending the Email on Android & iOS using Sendgrid, I'll have to create the same Email template on Android and iOS, twice, and it must be a pain.

I don't know how big the task is to implement the endpoint, but from the client's point of view, the endpoint is the best solution because it keeps the consistency across Dashboard, Android and iOS.

**Comment by ijunaidfarooq** [comment]
This is now resolved and new endpoint is working on [Resend Share Request](https://dash.evercam.io/swagger#!/cameras/POST_cameras_id_shares_requests_format).

It takes `camera-id`  and `email` of the user whom we are sending request again due to pending.

@liutingdu You can use this in Your App.. and can be implemented in Dashboard as well.

**Comment by liutingdu** [comment]
Thanks a lot! @ijunaidfarooq
