### ISSUE TITLE
GET /cameras and GET /cameras/{id} returns different rights

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-api#505]
Account A shares a camera with account B with full rights.

A changed the rights on account B to be 'Read-Only' from dashboard

Then ```GET /cameras/{id}``` indicates the camera is read only now ```"rights": "list,snapshot"```

But in response of ```GET /cameras```, for the same camera, it remains full rights ```edit,grant~list,grant~view,list,snapshot,view,grant~edit,grant~snapshot```

Seems it will be back to normal after ~10 minutes

**Comment by ijunaidfarooq** [comment]
This issue is related to cache and in API cache is updated after 10 minutes automatically that's why after 10 mins this seems normal ref : [API](https://github.com/evercam/evercam-api/blob/master/config/sidekiq.yml)

**Comment by mosic** [comment]
@ijunaidfarooq The line you linked isn't related to caching at all, we use Sidekiq for running async tasks in evercam-api.

The caching duration is 5 minutes, you can see it here: [lib/services.rb#L14](https://github.com/evercam/evercam-api/blob/7caf6f8c40cd997955ff59427e777af3bd94f2b8/lib/services.rb#L14).

This problem has been fixed in evercam-media (https://github.com/evercam/evercam-media/issues/192) so I'll close this issue.

**Comment by marcoherbst** [comment]
Thanks @mosic & @ijunaidfarooq  .... that makes sense.

Junaid, Milos' main point here is that he is in the process of recreating these endpoints in evercam media and we will be soon (tues / wed ?) redirect these ruby API endpoints to evercam media. 

In that context, it's better to close this task as he says, and move on to the next .... :) 

You might spot other opportunities where this is also true.
